[package]
name = "ezytutors"
version = "0.1.0"
authors = ["lwooden <lowell.wooden@gmail.com>"]
edition = "2018"

[workspace]
members = ["tutor-nodb", "tutor-db"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
