version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ezytutors
      POSTGRES_DB: ezytutors
      
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432